[libdefaults]
  default_realm = AUTH-LAB.LOCAL
  dns_lookup_kdc = false
  dns_lookup_realm = false
  rdns = false
  ticket_lifetime = 10h
  forwardable = false
  default_ccache_name = FILE:/tmp/krb5cc_authlab

[realms]
  AUTH-LAB.LOCAL = {
    kdc = kerberos:88
    admin_server = kerberos:749
  }

[domain_realm]
  .auth-lab.local = AUTH-LAB.LOCAL
  auth-lab.local = AUTH-LAB.LOCAL
